apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: codeengine-exp1
spec:
  # target identifies the knative service under experimentation using its fully qualified name
  target: default/sample-app
  strategy:
    # this experiment will perform a canary test
    testingPattern: Conformance
  criteria:
    # Other metrics:
    # mean latency of version should be under 0.5 seconds
    # error rate should be under 5%
    objectives: 
    - metric: iter8-system/mean-latency
      upperLimit: "100"
    - metric: iter8-system/error-rate
      upperLimit: "0.05"
  duration:
    intervalSeconds: 20
    iterationsPerLoop: 10
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: current