apiVersion: iter8.tools/v2alpha1
kind: Experiment
metadata:
  name: quickstart-exp
spec:
  # target identifies the knative service under experimentation using its fully qualified name
  target: default/sample-app
  strategy:
    # this experiment will perform a canary test
    testingPattern: Canary
    deploymentPattern: Progressive
    actions:
      # start: # run the following sequence of tasks at the start of the experiment
      # - library: knative
      #   task: init-experiment
      finish: # run the following sequence of tasks at the end of the experiment
      - library: common
        task: exec # promote the winning version
        with:
          cmd: kubectl
          args: 
          - "apply"
          - "-f"
          - "https://raw.githubusercontent.com/sushmarchandran/iter8/codeengine/samples/codeengine/{{ .promote }}.yaml"
          - "--kubeconfig=/kubeconfig/ce-kubeconfig.yaml"
  criteria:
    # Other metrics:
    # mean latency of version should be under 50 milliseconds
    # 95th percentile latency should be under 100 milliseconds
    # error rate should be under 1%
    objectives: 
    - metric: error-rate
      upperLimit: 0.1
  duration:
    intervalSeconds: 10
    iterationsPerLoop: 10
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: current
      variables:
      - name: revision
        value: sample-app-v1 
      - name: promote
        value: baseline
    candidates:
    - name: candidate
      variables:
      - name: revision
        value: sample-app-v2
      - name: promote
        value: candidate 
